### ISSUE TITLE
Website site should not overflow the screen

### ISSUE THREAD

**Issue by samagragupta** [samagragupta/Moviepedia#4]
Website site should be of screen size.

**Comment by meganindya** [comment]
Can I address this issue?

**Comment by samagragupta** [comment]
@meganindy Sure

**Comment by meganindya** [comment]
Should the website be totally scrollbar free, or only vertically scroll able?

**Comment by samagragupta** [comment]
only vertically scroll able

**Comment by meganindya** [comment]
Alright
